### ISSUE TITLE
The process is killed prematurely 

### ISSUE THREAD

**Issue by byronn-1** [openbcl/fds-dockerfiles#3]
## What are you trying to do
Hi, Firstly Thanks for creating this resource. I have been trying to run this in an AWS EC2 instance. I have successfully downloaded Docker, created a docker container and folder to store the file to be processed. 

## Describe your problem
So... the container environment clearly works or at least wants to work, although it starts up then after a few seconds throws the below message. I am reliably informed that the pyrosym environment generally stops with 'Killed' if there is something wrong. We have tested this file in the local environment and the simulation runs. 

[ec2-user@ip-0000000000 firesims]$ docker run --rm -it -v $(pwd):/workdir openbcl/fds
root@6174521d3e63:/workdir# fds test1.fds

 Starting FDS ...

 MPI Process      0 started on 6174521d3e63

 Reading FDS input file ...

Killed

I have listed the contents of the folder and found these files 
[ec2-user@ip-000000000 firesims]$ ls
scenario_b_natural_ventilation_two_by_one_2m.binfo    scenario_b_natural_ventilation_two_by_one_2m.sinfo
scenario_b_natural_ventilation_two_by_one_2m.end      scenario_b_natural_ventilation_two_by_one_2m.smv
scenario_b_natural_ventilation_two_by_one_2m_git.txt  test1.fds

## Expected behaviour
I was hoping this would run and process the FDS files as suggested. Is there any thing I should know?

## Additional context
Is there a way of getting the FDS file out of pyrosym or any settings that need to be applied to the file in its local environment in order for it to run like this? 
The way we got the FDS file from the local environment was- File > Export > FDS file

## Desktop Environment
- Operating System: 
- Docker-Version: Docker version 20.10.7, build f0df350
- Docker-Images: openbcl/fds   latest    3650793f44cd   4 months ago   431MB

**Comment by rweisse** [comment]
Hi @byronn-1

At first glance, it looks like you did everything right. Unfortunately I have no experience with AWS EC2. However I would be very happy if it worked as this could also be interesting for my company.

### So let's try to debug the bug :-)

You should know that FDS has some requirements for the host operating system. Your instance should have enough memory. Most of our simulations require 8-24GB of memory (sometimes more). If there is not enough memory, FDS will simply crash. For computers with less memory, it may help to activate SWAP to compensate for the lack of memory. However, this is theoretically accompanied by a loss of speed. In addition, SWAP is often not available in cloud instances.

Therefore I am interested in the RAM size of your instance. You should get RAM information by executing the following command:
```bash
cat /proc/meminfo
```

Furthermore, I would like to know whether FDS can be executed at all. Please run the following command and post the terminal output in your answer:
```bash
docker run --rm openbcl/fds fds
```

### Known errors and possible solutions
In the past, individual containers were terminated (KILLED BY SIGNAL: 7). On our Linux computers it has helped to increase shared memory. Unfortunately, you only get "KILLED" and not "KILLED BY SIGNAL 7". Nevertheless, you should try to extend your command with the parameter `--shm-size=<SIZE>`. For example, if your instance has 16GB of memory you could set it to 8192M. Your command would then be:
```bash
docker run --rm --shm-size=8192M -it  -v $(pwd):/workdir openbcl/fds
```

Furthermore you should try to set the stacksize to unlimited. [Here you will find more information](https://github.com/firemodels/fds/issues/6265). Your command would then be:
```bash
docker run --rm --ulimit stack=-1 -it  -v $(pwd):/workdir openbcl/fds
```

Last but not least you could try to combine both:
```bash
docker run --rm --ulimit stack=-1 --shm-size=8192M -it  -v $(pwd):/workdir openbcl/fds
```

### Additional context
Do you mean [PyroSim](https://www.simtego.de/software/pyrosim/)? It should be possible to create or extract the file as you have described. As far as I know no platform-dependent setting is stored in the FDS file. We also create the files on Windows systems (sometimes manually and sometimes with PyroSim). The simulations are then executable under Linux as well as Windows or Docker.

**Comment by byronn-1** [comment]
Yes sorry I was meaning PyroSim. 

Here is the info you asked for, it looks like you were correct that there is nowhere near enough RAM. I will try and upgrade the instance. Unless there is anything else you have spotted here?

[ec2-user@ip-0000000000 firesims]$ cat /proc/meminfo
MemTotal:         988672 kB
MemFree:          567020 kB
MemAvailable:     671672 kB
Buffers:               0 kB
Cached:           215852 kB
SwapCached:            0 kB
Active:           108736 kB
Inactive:         210656 kB
Active(anon):       2176 kB
Inactive(anon):   100876 kB
Active(file):     106560 kB
Inactive(file):   109780 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:                 0 kB
Writeback:             0 kB
AnonPages:        103576 kB
Mapped:            44476 kB
Shmem:               432 kB
KReclaimable:      31848 kB
Slab:              57888 kB
SReclaimable:      31848 kB
SUnreclaim:        26040 kB
KernelStack:        2368 kB
PageTables:         5052 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:      494336 kB
Committed_AS:     797360 kB
VmallocTotal:   34359738367 kB
VmallocUsed:        6348 kB
VmallocChunk:          0 kB
Percpu:             7808 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:       83968 kB
DirectMap2M:      964608 kB



[ec2-user@ip-000000000 firesims]$ docker run --rm openbcl/fds fds

 Fire Dynamics Simulator

 Current Date     : April  5, 2022  11:08:03
 Revision         : FDS6.7.7-0-gfe0d4ef38-release
 Revision Date    : Thu Nov 18 17:10:22 2021 -0500
 Compiler         : Intel ifort 2021.4.0
 Compilation Date : Nov 19, 2021 08:15:06

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Enabled; Number of OpenMP Threads:      1

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.4 for Linux* OS

 Consult FDS Users Guide Chapter, Running FDS, for further instructions.

**Comment by rweisse** [comment]
Yes, that's right. The instance has just under 1GB of RAM. That is definitely insufficient. You can also see that SWAP is not enabled (but I expected that).
```
...
SwapTotal: 0 kB
SwapFree: 0 kB
...
```

You could try to enable swap before purchasing more memory on your instance. That could be a lot cheaper for testing purposes. Then you should be able to run FDS even if the instance only has 1GB of memory. However, it will then most likely run slower.

From a cloud provider's point of view, SWAP is a very annoying thing. Therefore, SWAP is usually deactivated. For FDS, however, SWAP is very important. The demand for memory can fluctuate during a simulation. As the simulation progresses, the complexity of the calculation often increases. Therefore, it can happen that the memory requirement fluctuates. If there is not enough working memory available, the simulation will abort.

Therefore, I configure SWAP on each of our Linux workstations just to be save in the following way (Ubuntu 20.04.3 LTS):

#### Check filesystem size (SSD/HDD)
Of course your swapfile should not be bigger than your disk space ;-)
```bash
df -H
```

#### Create swapfile
120GB is quite big - 20GB should also be enough if your memory is increased in the future ;-)
```bash
fallocate -l 120G /swapfile
# or if you have not much free hdd space
fallocate -l 20G /swapfile
```

#### Set access rights
```bash
chmod 600 /swapfile
```

#### Format swapfile
```bash
mkswap /swapfile
```

#### Enable swap
```bash
swapon /swapfile
```

#### If you like to auto-enable swap after each reboot
I am not sure if this really works on AWS EC2.
```bash
echo "/swapfile swap swap defaults 0 0" >> /etc/fstab
```

**Comment by byronn-1** [comment]
Thanks. With your guidance I have had to take a deeper dive into EC2 and Linux to get a better understanding of potential instance parameters. So far I understand that creating a swap file on EC2 is possible. I just need to work out the correct balance of RAM swap and persistent storage (what AWS calls EBS) so it works but doesn't cost the earth. I will have a play with a few instances and let you know how I get on. Many thanks for your input thus far, I doubt I would have figured this out on my own.

**Comment by rweisse** [comment]
Thank you @byronn-1 for your feedback. I'll keep my fingers crossed that it works soon. I think your insights would be interesting not only to me. There are probably many people out there who would like to know how it works. I am already very curious.

**Comment by byronn-1** [comment]
Hi @rweisse I just wanted to check in again. I have increased the size of the EC2 instance to one that has more favourable memory, AWS calls it an r4 large it has 15GB of RAM. Unfortunately as one may imagine this is not in their free tier!  I haven't played with the swap file yet because I was in a hurry to run it, but will do so if this iteration fails. So far the process seems to be running quite fast.

**Comment by rweisse** [comment]
I'm definitely very happy that FDS over Docker on AWS EC2 seems to work now!

I just googled EC2 Instance Types and found the following site: https://aws.amazon.com/ec2/instance-types/?nc1=h_ls

There I could find your configuration:

Instance | vCPU | Mem (GiB) | Storage | Networking Performance (Gbps)***
-- | -- | -- | -- | --
r4.large | 2 | 15.25 | EBS-Only | Up to 10

To increase the speed of your simulation you could use both cpu cores in a more efficient way. At the moment both cores should be used by OpenMP already. If you were to build your simulation with two meshes, you could also start it with Intel MPI, which would double the speed of the calculation.

```bash
docker run --rm -e OMP_NUM_THREADS=1 -it -v $(pwd):/workdir openbcl/fds
```
```bash
mpiexec -n 2 fds test1.fds
```

There are pros and cons about splitting the simulation in different meshes. And there are pros and cons about either using OpenMP or Intel MPI or both at once. For this I recommend reading the FDS USer guide: https://github.com/firemodels/fds/releases/download/FDS6.7.7/FDS_User_Guide.pdf

To be safe from crashes, you should also think about setting the DT_RESTART parameter in the FDS file.

**Comment by rweisse** [comment]
@byronn-1 I am closing this issue, since it seems to work now.

**Comment by byronn-1** [comment]
Hi sure thing, I had replied but for some reason it hadn't sent I have since lost the CLI read out.

What I had wanted to get across was that this process had worked including creating the swap file, although I had not got round to testing multiple meshes. I had taken some advice off a friend studying towards his AWS architect qualification. He recommended that AWS Fargate would have been suitable for this application also.

"I think the way that Fargate tasks are intended to work is that you choose your initial image/task size which seems to range from: 0.25vCPU and 0.5GB memory to the biggest 4vCPU and 30GB memory. AWS then charge you by the second apparently.
They all come with a default bit of ephemeral storage (20GB) and if you need more persistent storage then you pay for EBS or EFS or write it to a database (depends on how your application is written)."

This could be another way others could tackle this issue in the future.

Thanks for all your advice.

**Comment by rweisse** [comment]
You are welcome. If you have problems again, just get in touch.
